### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by spekkie2002** [spatie/laravel-activitylog#13]
Hi,

Love the package, good job guys!
Wouldn't it be a good idea to have the option to automatically add all attributes, without the need to specify all of them manually? 

Kind regards

**Comment by sebastiandedeyne** [comment]
Under the hood, the package uses an `attributesToBeLogged` method to read the `$logAttributes` property. If you want more advanced control over logging attributes, you could simply overwrite that method instead of using the property.

https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/DetectsChanges.php#L25-L31

To log all attributes, you could simply return a `toArray` of the model.

```php
public function attributesToBeLogged(): array
{
    return $this->toArray();
}
```

**Comment by spekkie2002** [comment]
Okay thanks! 👍
