### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by sjosen** [spatie/laravel-activitylog#160]
Hello

Can this be used for Lumen with smal changes? I get an error 

    Call to undefined function Spatie\Activitylog\config_path()

Thx in advance

**Comment by freekmurze** [comment]
I don't use Lumen myself, so I don't know for sure.

But I guess this package can be used if you write your own Lumen compatible service provider.

**Comment by xcaptain** [comment]
It works well with lumen 5.4.*, the only problem I've met is 
`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\\Auth\\AuthManager` which is caused by [https://github.com/spatie/laravel-activitylog/blob/master/src/ActivityLogger.php#L33](https://github.com/spatie/laravel-activitylog/blob/master/src/ActivityLogger.php#L33) and can be solve by adding
```php
$app->singleton(Illuminate\Auth\AuthManager::class, function ($app) {
    return $app->make('auth');
});
```
to bootstrap/app.php.

The solution was comes from https://github.com/tymondesigns/jwt-auth/issues/561

**Comment by omar-faruk-sust** [comment]
Hi @xcaptain , Can you give me instruction, how can i integrate this package on lumen please? it will be helpful. Thanks in advance.

**Comment by Gummibeer** [comment]
How about a special lumen section or splitted readme how to adjust/use it with lumen?

**Comment by xcaptain** [comment]
@omar-faruk-sust sorry for being late, can you paste your problems, in my case this package works well with lumen, below are my config steps.

1. add service provider to bootstrap/app.php
`$app->register(Spatie\Activitylog\ActivitylogServiceProvider::class);`
1. copy config files
`cp vendor/spatie/laravel-activitylog/config/activitylog.php config/`
1. manual specific config file, edit bootstrap/app.php
`$app->configure('activitylog');`
1. add a help function to bootstrap/app.php
```php
if (! function_exists('config_path')) {
    function config_path($path = '')
    {
        return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
    }
}
```

I'm using lumen 5.5.2 and activitylog 2.5.1

**Comment by warifp** [comment]
**Thanks!**
