### ISSUE TITLE
Integration with laravel-permission

### ISSUE THREAD

**Issue by kjdion84** [spatie/laravel-activitylog#182]
I am having a bit of trouble integrating this with your `laravel-permission` package.

I have CRUD in place to manage roles. The role create/edit form simply has an array of `permissions` which I use to update in the database like this:

```
$role = UserRole::create([
    'name' => request()->input('name'),
]);
$role->permissions()->sync(request()->input('permissions'));
```

It was working fine when I was using the `Role` model direct, but now I am getting a `Column not found` database error when attempting to create/edit a role.

Here is my UserRole class:

```
namespace App;

use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Permission\Models\Role;

class UserRole extends Role
{
    use LogsActivity;

    /**
     * The attributes that should be logged.
     *
     * @var array
     */
    protected static $logAttributes = ['name', 'permissions'];
}
```

Also, I noticed that it does not log the permission changes in the `properties` column of the activity log. Is there a way I can accomplish this?

**Comment by kjdion84** [comment]
Nevermind I think I've got it now. I just renamed this class to `Role` as well and will use the manual logging functions in order to log the `permissions`.

**Comment by kjdion84** [comment]
One last question - is it possible to set this up so it detects changes in hasMany relationships so I can still utilize `LogsActivity` for my `permissions`?

**Comment by kjdion84** [comment]
Just did it manually.

**Comment by lionwalker** [comment]
Did you wrote manual logging function on the vendor folder? I'm having the same issue. can you tell what did you do to accomplish it.

**Comment by Gummibeer** [comment]
@kjdion84 it's right - until now we've found no way to log relations. The main reason is that eloquent doesn't throw any event for this (if this has/will change it will get possible).
But I think that this won't happen in near time/at all because there are so much ways to save a relation and it's a kind of philosophic discussion on wich model the event(s) should be thrown.
And one of the most common cases to save request data won't support this `'role_id' => $request->get('role_id')`. 

@lionwalker starting this discussion in two threads #331 isn't very helpful because they don't link each other.
So the easiest way would be to create your own issue and link the others. Or discuss in only one - which isn't recommended for longer discussions/bigger problems because these issues are closed already.
