### ISSUE TITLE
how to use function "subject" in Activity.php

### ISSUE THREAD

**Issue by jespersgaard** [spatie/laravel-activitylog#216]
hello

i have used the "casuer" function to get information from the model that causes the activity log, but for some reason the "subject" function doesn't work for me

**Comment by bbashy** [comment]
Subject is just a polymorphic relation. What exactly doesn't work?

**Comment by shiroamada** [comment]
I also come to this question.

E.g I have 
`App\Entities\Business` and `App\Entities\Blog` store into `subject_type`

My Business Table, I want to get `business.name`, but my in my Blog table I want to `blog.title`
since two tables have differents column name, how do I display both in one table? Since two tables are using different column name.

I tried `subject.title`, I only able to display Blog title, but for Business name it is not able to retreive it.

I pulled with Datatables.



![](https://i.imgur.com/S9YLVar.png)

**Comment by bbashy** [comment]
@shiroamada I don't think your problem is related to the OP's but to answer your query, I ended up making accessors on the models. This makes it easy to pull out the contents.
```
@foreach($activities as $activity)
    <li class="activity-item">
        <span class="type">
            <span class="val">{{ $activity->subject->short_name }}</span>
            <small>{{ $activity->created_at->diffForHumans() }}</small>
        </span>

        <span class="info">{{ $activity->subject->activity_sentence }}</span>
    </li>
@endforeach
```

**Comment by shiroamada** [comment]
ok, make the accessors really a good tip! Thanks! These info really help for beginner like me. Can included in your readme information. (Y) Sorry for hijack for this thread.

**Comment by introwit** [comment]
@jespersgaard are you still facing the issue? Can you elaborate more on what exactly doesn't work?
