### ISSUE TITLE
support for logging attribute change in json fields

### ISSUE THREAD

**Issue by saqueib** [spatie/laravel-activitylog#274]
Thanks for the great project, I wanted to know, does it supports to log changes in JOSN field type, I have tried following but it didn't work.

```php
use LogsActivity;

protected static $logAttributes = ['name', 'in_short', 'meta->progress'];
```

Keep up the great work 👍

**Comment by freekmurze** [comment]
That isn't supported atm, I'd accept a PR if the code to makes this work is simple.

**Comment by rjcrystal** [comment]
It logs json fields as empty, even with changes. Is this expected behaviour ? 
model configuration 
`
    use LogsActivity;
    protected static $logAttributes = ['*'];
`

**Comment by Gummibeer** [comment]
@rjcrystal could you please open a new issue? Even if they kind of belong to each other the original topic is a feature request and your's is a bug/question.

**Comment by Gummibeer** [comment]
@saqueib I've reopened this issue to keep it in the feature request line. But I can't promise when or even that it will come.

**Comment by Gummibeer** [comment]
@ReeceM happy to hear this! 😊
I think that it should be added via a new method called in https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/Traits/DetectsChanges.php#L120-L143
Something like the already implemented date serialization.

If you need any more details just ask. Or if you have some code just open the PR and we will discuss it.

**Comment by ReeceM** [comment]
@Gummibeer, awesome, thank you. 

I will have a look at adding it there as a new method then 👍 . 

I will also ask for more details too probably :)

**Comment by ReeceM** [comment]
Hi @Gummibeer, if this is added for to log a specific attribute, would it also be preferred to be able to ignore a specific attribute in the JSON ? 


I don't think the below would account for ignoring keys in a JSON object/array

 https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/Traits/DetectsChanges.php#L47-L49

**Comment by Gummibeer** [comment]
To keep the scope simple I would like to stick to exactly what the issue author requested.
So only add a JSON attribute sub-key. What I've forgot. The main attribute has to be used in method that collects all attributes to log.

https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/Traits/DetectsChanges.php#L27-L52

And it would be awesome if the `logOnlyDirty` works with the JSON attributes.
I would also be fine with a limit of depth. So that it's only possible to access the first level of JSON attributes.

**Comment by ReeceM** [comment]
Okay, I won't account for ignoring, would that be welcomed as a separate feature addition?

With the depth, I have managed to make it go as far down as put in the sub-key of the `$logAttributes`.

In terms of the `logOnlyDirty`, is that for when it is included in `$logAttributes` or for any JSON that is put into the model?

**Comment by Gummibeer** [comment]
As a separate it's welcomed. But I would like to keep the hacktoberfest PRs simple to review and merge them fast.

I mean this: https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/#logging-only-the-changed-attributes
So that if it's enabled and `attribute` has changed in total but `attribute->subkey` didn't it won't log it. But also with this I would be fine with a new PR or that's a limitation of the feature.

**Comment by ReeceM** [comment]
Okay, so far from what I can tell is that it won't update the whole `attribute` when the sub-key hasn't changed.

I will write some tests to account for this addition for the changes.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.9.0
