### ISSUE TITLE
Complementary Package Activity Log viewer.

### ISSUE THREAD

**Issue by chriscalip** [spatie/laravel-activitylog#328]
Who wants it? Can we have it?

**Comment by freekmurze** [comment]
Providing a UI is out of scope for this package.

**Comment by Gummibeer** [comment]
@freekmurze  That's why *Complementary*. ;)
I think that this is more or less a community question and development. Or wasn't it meant like this @chriscalip ?

In general it would be good - my major problem here is *frontend* - There are millions of frameworks, combinations, themes, styles, languages and so on. So this will be just an idea of how to do it or a part of my backend-app that will never work and look like the other pages.
That's why I think that this shouldn't be done. It's too much work for something that's ok for prototyping but not for productive usage. If I'm wrong (I'm backend dev) please tell!^^

**Comment by chriscalip** [comment]
@Gummibeer
I am mostly a backend dev also; But mostly I don't see why the proposed ui just assumes it a partial blade; in other words package ui exports a blade file that assumes a developer adds in `@extends('layouts.your-theme')`. It's just a time saver for a repeatable task.

**Comment by Gummibeer** [comment]
That could work for most blade based frontends - even there not all. Also with this you have to define used CSS framework and other classes. Without adjustments this will not look nice in most themes.

For all react, vue, angular, polymer based frontends this will never work. Cause of the fact that most backoffice frontends have a lot of realtime data most of them are based on any kind of SPA.

That's why I say that this could be useful for some, but in most cases (I think) that this isn't something that saves lives in production. In most cases you already have a simple way for tables, filters in a backoffice cause it's nothing more. So for an existing frontend this is no real work.

https://www.datatables.net as a simple example will reduce your work to a onetime styling, copy'n'paste and adjusting the base query/resultset.

**Comment by chriscalip** [comment]
@Gummibeer Target users are mostly developers not concerned with looks; more of get an overview of the activity-logs and go on with our days. Package ui serves as a plug-in-play way to see activity logs or as an example package showing how to expose activity logs.

**Comment by damms005** [comment]
@freekmurze I built a UI just for this. Leveraged on the awesomeness on TailwindCss. Features search filters, etc. PR welcomed?

**Comment by Gummibeer** [comment]
@damms005 like said a UI isn't in the scope of this package. But we would be happy if you create your own package and we could link it.

**Comment by peterthomson** [comment]
I get that the Activity package is non-opinionated on how the activity is rendered and displayed. One way that other non-opinionated packages allow for users to learn and explore is to publish or allow the community to publish examples, and/or link to a library of common usage.

**Comment by Gummibeer** [comment]
@peterthomson everyone is allowed to post his references in at least this issue.
If we will move, some, into the readme or real docs will not be guaranteed.
If you write a tutorial or something with an explanation around the code it could be more helpful for others.

**Comment by damms005** [comment]
@Gummibeer @freekmurze Please show some love to this nice UI for Spatie's activitylog: [laravel-activitylog-ui](https://github.com/damms005/laravel-activitylog-ui)

Please critique the package and help improve ❤️

**Comment by rxng** [comment]
@damms005  unfortunately voyager only
