### ISSUE TITLE
attributes with some Encoding problem

### ISSUE THREAD

**Issue by mozielin** [spatie/laravel-activitylog#355]
Hi, I used to log some subject with Chinese ，and I got activity log with this 
company_name":"\u8d85\u79e6\u4f01\u696d\u80a1\u4efd\u6709\u9650\u516c\u53f8"
How can I let it to become readable?

**Comment by AlexVanderbist** [comment]
Hi @mozielin! 

I just tested this and I didn't have any problems logging or retrieving activity with Chinese characters in it. Can you share some failing example code?

I'm no expert when it comes to character sets but are you sure you it's not being converted to unicode somewhere else? Also, are you sure the database is using a character set that supports the Chinese characters? I quickly read through https://medium.com/@elye.project/support-chinese-characters-end-to-end-3d69ef0ada3a and it seems like a great starting point.

(Finally, most open source maintainers prefer not being e-mailed about issues ;)

**Comment by mozielin** [comment]
Here is my code...I used to log customer files
![2018-03-22_09-53-46](https://user-images.githubusercontent.com/33715982/37746833-12bb2ef8-2db7-11e8-95d1-b08cbe912ab1.png)

Customer files with Chinese is fine
![2018-03-22_09-56-51](https://user-images.githubusercontent.com/33715982/37746904-638cd746-2db7-11e8-9f18-ad13b731af17.png)

when data changes ，the log properties show encoding attributes like...
![2018-03-22_09-58-51](https://user-images.githubusercontent.com/33715982/37746952-a9958aee-2db7-11e8-9d8e-1ac2948c0ab3.png)

You can see in company_name there are not Chinese~

Any idea?  

(BTW I`m sorry about emailed about issue，I didn`t notice that，I apologize and thanks for replied)

**Comment by AlexVanderbist** [comment]
Hi, I had another look today and it turns out that PHP's `json_encode()` will escape unicode characters (= Chinese chars). However once the json is put through `json_decode()` it will be converted back into  the original unicode characters. This means when outputting the properties somewhere in your application they will be regular Chinese characters again. 
Have a look at this snippet: https://3v4l.org/44YVN#output

As possible a solution we could add the `JSON_UNESCAPED_UNICODE` flag to the `json_encode()` method. However I am not sure what other impact this will have... I'll check and there are no side-effects add that in :)
