### ISSUE TITLE
Subject not showing if using softdeletes

### ISSUE THREAD

**Issue by indradanadx** [spatie/laravel-activitylog#445]
I have problem using laravel-activitylog

this is my controller
`$activitydata = Activity::with('subject')->orderBy('created_at','DESC')->get();`

im try to showing subject but this not showing if using softdeletes on model
and in config activitylog.php I have made this function true

`'subject_returns_soft_deleted_models' => true,`

but if i comment
`use SoftDeletes;` on model subject working

**Comment by Gummibeer** [comment]
Hey, the moment you comment the trait in your subject model solves your issue?
In this case it shouldn't have something to do with the config. This config value controls only if the `withTrashed()` scope is used or not.
https://github.com/spatie/laravel-activitylog/blob/68eb6e65382f94fe86ce5ff6572159f80d024ba9/src/Models/Activity.php#L28-L35

Otherwise the config value `true` and not available scope method (commented trait use) should throw an exception - unknown method call.

All the behavior is also unit tested at
https://github.com/spatie/laravel-activitylog/blob/68eb6e65382f94fe86ce5ff6572159f80d024ba9/tests/LogsActivityTest.php#L171-L190

Could you provide more details - which model is deleted and to sure that the soft delete works do `SubjectModel::where('id', 'the id of the referenced subject in your activity')->withTrashed()->get()` and see if it returns the right model or if even this fails!?

**Comment by indradanadx** [comment]
withTrashed() worked thanks @Gummibeer

**Comment by Gummibeer** [comment]
@indradanadx Ok, is your issue solved now?

**Comment by indradanadx** [comment]
yeah is solved
