### ISSUE TITLE
Add indexes to causer and subject id/type columns

### ISSUE THREAD

**Issue by ashgibson** [spatie/laravel-activitylog#454]
As the causer and subject columns use polymorphic relationships would it make sense to add indexes to these to improve queries or does this cause an overhead on insertion?

**Comment by Gummibeer** [comment]
Hey,
thanks for your suggestion/idea. For me I would reject this because it's very easy to add indexes to these columns in your own migration. But in package it would introduce it to everyone and indexes aren't just positive. Primary on massiv data holding table with string columns that have to be indexed. And I bet that most users won't care if the log backend is a bit slower during read but faster during write and also a more lightweight database server.

And so far I got @freekmurze he wants to keep this package as simple and lightweight as possible.

**Comment by freekmurze** [comment]
I indeed like to keep the package simple. if you need indexes, add them manually in your app.
