### ISSUE TITLE
Add Field to Activity_logs table

### ISSUE THREAD

**Issue by RubickLinh** [spatie/laravel-activitylog#469]
Thank your package, it very nice. In my project, i want each shop have many log. So i add shop_id in table activity_logs. I use log in Model like:
 activity('Update Order')
                ->performedOn($order)
                ->causedBy(Auth::user())
                ->withProperties( $data)
                ->log('Order updated '. 'ID:' . $order->id); 
But it can't save shop_id in database. So any way to store shop_id in table activity_logs by using log in Model. Can you help me?. Sr my english not good, i from Vietnamese. Thank you

**Comment by Gummibeer** [comment]
This duplicates #462 and relates to #466 - there are ideas how to solve it.
Also one we want to implement in this package, but haven't done yet. If you want it done by a chained method you can extend `ActivityLogger` and rebind it to the app container with your new method `forShop()`.

I will close this because the new feature related discussion should be done in #462 and except of the already listed ideas in other issues I don't see any other way how to solve it at the moment.
