### ISSUE TITLE
Document removal of HasActivity trait in v3 in UPGRADING

### ISSUE THREAD

**Issue by mpryvkin** [spatie/laravel-activitylog#477]
HasActivity trait has been removed in v3 but that is not mentioned in the [UPGRADING.md](https://github.com/spatie/laravel-activitylog/blob/master/UPGRADING.md).

**Comment by Gummibeer** [comment]
@mpryvkin thanks for mention it. Yes, we've only documented the changes in the `CausesActivity` trait. The `HasActivity` trait was only a duplicate of it because we had naming conflicts.
These are solved now - so we haven't dropped it without replacement.

But yes, it would be nice to add to to the [UPGRADING.md](https://github.com/spatie/laravel-activitylog/blob/master/UPGRADING.md) and [CHANGELOG.md](https://github.com/spatie/laravel-activitylog/blob/master/CHANGELOG.md).

**Comment by mpryvkin** [comment]
@Gummibeer Sorry, you're right. I have meant UPGRADING not CHANGELOG.

**Comment by Gummibeer** [comment]
@mpryvkin mix of both - it needs to be in both of them. 😉 
Will you do it? Or should I write it?

**Comment by mpryvkin** [comment]
@Gummibeer I can do it if you want.

**Comment by Gummibeer** [comment]
@mpryvkin thanks for your work! :) I've merged it.
