### ISSUE TITLE
Issue in version 3.2

### ISSUE THREAD

**Issue by amit-aika** [spatie/laravel-activitylog#481]
when I tried to save logs in database, it is showing error

> {"error":true,"message":"Call to a member function retrieveById() on null","file":"\/application\/vendor\/spatie\/laravel-activitylog\/src\/ActivityLogger.php","line":148}

After updating version from 3.1.2 to 3.2.0 
Please help as soon as possible. Here is the way by which i am using

```
    /**
     * Save Logs description
     * @return [type] [description]
     */
    public function saveLogs($description, $properties, $type)
    {
        $id = \Auth::user()->getKey();
        activity($type)
            ->withProperties($properties)
            ->log(json_encode($description));
    }
```

**Comment by Gummibeer** [comment]
Hey,
Have you disabled your auth guard? Your exception means that your auth guard doesn't have a provider.
A fix is easy but I would also want to understand what's going wrong.
Can you give some more details: laravel or lumen, web or cli and if you have changed something in your auth config.

**Comment by Gummibeer** [comment]
@amit-aika could you try if `dev-fix-normalizecauser-without-provider` solves your issue? I'm not happy but its' right because `guard()` returns `\Illuminate\Contracts\Auth\Guard|\Illuminate\Contracts\Auth\StatefulGuard` both don't have to define `getProvider()` which is defined in `\Illuminate\Auth\GuardHelpers` trait.

And as a hint:
The current user is set by default as causer, done in the `\Spatie\Activitylog\ActivityLogger::getActivity()` method. And if you want to set another user and already have it's model, like `Auth::user()` pass it and not just the ID. This saves you a DB request.

**Comment by amit-aika** [comment]
Thank You @Gummibeer
