### ISSUE TITLE
Incompatibility with Spark 8

### ISSUE THREAD

**Issue by piovani** [spatie/laravel-activitylog#519]

**Comment by Gummibeer** [comment]
Hey,

could you provide any details?

**Comment by piovani** [comment]
Yes, Laravel Spark (https://spark.laravel.com), it works with the standard user of laravel by implementing it. If we put the ActiveLog to listen to that model, using some field that the spark uses it of the problem. In my case I used the unique email, which is the authentication form of my system, where spark manages. With ActiveLog listening to this field, Spark runs twice and does not let register for mail duplicity. This only happens with version 8 of Spark, the version Dev does not happen this, but this is an unstable version.

**Comment by Gummibeer** [comment]
Ok, but the activity log only reads from the subject model. So if spark complains about duplication it sounds more like a spark bug. Primary if it's solved in the current dev version.
Because Spark is a proprietary package without a public issue tracker (so far I see) it seems that you have to contact the spark team via email or something like this.
