### ISSUE TITLE
[Suggestion] Property sorting and filtering?

### ISSUE THREAD

**Issue by sweatyc** [spatie/laravel-activitylog#524]
For the purpose of using this as analytics tool, it will be greatly useful if the property can be sorted and filtered. For example:

`Activity::inLog('button_clicked')->sortByProperty('user_age', 'desc')->get();`
`Activity::inLog('button_clicked')->whereProperty('user_sex', 'male')->get();`
`Activity::inLog('button_clicked')->wherePropertyIn('user_age', [18, 30])->get();`

I think this should be possible using Laravel's [collection](https://laravel.com/docs/master/collections#method-where) sorting and filtering? (Although it seems won't be very efficient for large amount of logs, since the properties are stored as text in database)

Or I should just use sth like [nested collection](https://coderwall.com/p/favqga/sorting-nested-laravel-collections) sorting/filtering?

**Comment by Gummibeer** [comment]
If you are on MySQL 5.7 you should check out the features that come with the JSON column type.
To let this work we/you should change the column type in the migration.

But after this you can query the JSON like "columns" `where('properties->gender', 'male')`.
I'm not sure if this will also work for sorting. At least with PHP collections it does. If it's for any UI it could be more performant to do the sorting in the frontend, underscore js does an awesome job.

Because using this package for analytics and the usecase isn't common I wouldn't change anything in the package itself, except of the migration.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.6.0
