### ISSUE TITLE
Activity Log Migrate not working

### ISSUE THREAD

**Issue by ahmetshen** [spatie/laravel-activitylog#548]
Hello there. after the changes made yesterday yesterday I am getting error in migrate after package installation. 

https://prnt.sc/nurkoq

**Comment by ahmetshen** [comment]
$table->text('properties')->nullable();
this change after work

**Comment by Gummibeer** [comment]
MariaDB supports JSON columns since v10.2.7 https://mariadb.com/kb/en/library/json-data-type/

This migration is only a stub and could to have be changed depending on your local setup. Because the migration itself is correct and it's not part of this package to map the correct real column type depending on the used DB I don't see what we could do?
https://laravel.com/docs/5.8/migrations#columns

After a quick search it looks like another package [ybr-nx/laravel-mariadb](https://github.com/ybr-nx/laravel-mariadb) is required to fully support MariaDB in laravel.
https://stackoverflow.com/questions/42425667/mariadb-json-support-in-laravel

**Comment by ahmetshen** [comment]
@Gummibeer thank you for answer
