### ISSUE TITLE
Viewing Activity Logs?

### ISSUE THREAD

**Issue by GalacticSun** [spatie/laravel-activitylog#552]
Hi, just curious what you guys recommend for viewing the saved activity logs.
Is there a frontend web page to easily view logs recorded with this package?
Thanks.

**Comment by Gummibeer** [comment]
Because of the different possibilities to use this package we don't provide any view. The simplest solution would be a simple blade view where you loop `@foreach()` over your activities related to a single model, type, channel or all and render any kind of table, list or whatever you need.
In more advanced solutions you can use something like list.js, dataTable.js or any SPA approach to load the activities with an async request, add filter/Search options and render only the matching ones.

**Comment by GalacticSun** [comment]
Ok, np, I thought so.  Thanks!
