### ISSUE TITLE
How to update database table structure?

### ISSUE THREAD

**Issue by bessone** [spatie/laravel-activitylog#553]
I saw the database changes in version 3.6.0, I have 3.5.0 how can I update the table structure? After launching composer update is there any way to do it automatically without losing data?

Thanks!

**Comment by Gummibeer** [comment]
Hey, we have only changed some column types - at all they should be compatible with the old ones.
Because the migration is only a stub and nothing final we decided to don't create an update migration but only change the default one.
The recommended behavior would be to:
1. backup your database
2. require `doctrine/dbal` https://laravel.com/docs/5.8/migrations#modifying-columns
3. create a new migration in your project, the up method should be similar to this:
```php
Schema::create(config('activitylog.table_name'), function (Blueprint $table) {
    $table->bigIncrements('id')->change();
    $table->bigInteger('subject_id')->nullable()->change();
    $table->bigInteger('causer_id')->nullable()->change();
    $table->json('properties')->nullable()->change();
});
```
4. run the migration
5. check your table structure and content
