### ISSUE TITLE
could not be converted to string

### ISSUE THREAD

**Issue by mortezamim** [spatie/laravel-activitylog#558]
Hi guy's, I'm trying to simply call this function.

`activity()->log('Look mum, I logged something');`

but i have this error

> ErrorException (E_RECOVERABLE_ERROR)
Object of class Illuminate\Auth\GenericUser could not be converted to string

can anyone help me?

**Comment by Gummibeer** [comment]
Hey,

could you provide a full stack trace? Without we can't know where this error is thrown.
But if I have to guess I would say that the default user resolver used for the causer has an error.

**Comment by mortezamim** [comment]
you can find full stack trace here
[Crash.txt](https://github.com/spatie/laravel-activitylog/files/3317822/Crash.txt)

Thanks for answering

**Comment by Gummibeer** [comment]
Hey,

if I got your stack trace right the exception is thrown in laravel core logic. The user provider generates an instance of `\Illuminate\Auth\GenericUser` which is wrongly passed into `Illuminate\Database\QueryException:formatMessage()` and there it's treated like string but doesn't contain a `__toString()` method.

Because there are no method parameters listed you should try to debug the part from `#62` to `#68` in your stack trace.

**Comment by mortezamim** [comment]
@Gummibeer 
i figured out my mistake and fixed the problem by changing provider for 

> config -> auth.php

`'providers' => [
        'user' => [
            'driver' => 'eloquent',
            'model' => \App\Models\User::class,
        ],
//        'user' => [
//            'driver' => 'database',
//            'table' => 'user',
//            'model' => \App\Models\User::class,
//        ],
    ],`

ty for answering.
