### ISSUE TITLE
Write old logs to file

### ISSUE THREAD

**Issue by JBtje** [spatie/laravel-activitylog#634]
I've been using this package for over a year now, and my log database is getting pretty large. Due to regulatory rules, I'm not allowed to delete the old logs. And due to increased use of the app, the log database grows exponentially.

Question: Are you aware of a package that is able to write **part of the logs** to a file and remove them from the database?

e.g. write the oldest 1.000.000 logs to a backup file and remove those from the logs table. Or write all logs of week 40 to a file, etc. I've been doing this manually, however it is a boring and repetitive task.
Note: I'm not looking for a solution that backups the full database, those are plenty around.

**Comment by Gummibeer** [comment]
I don't know any package but it's a simple artisan command. You could copy and adjust the package cleanup command.
https://github.com/spatie/laravel-activitylog/blob/master/src/CleanActivitylogCommand.php

Instead of directly call `delete()` you could loop via `each()` over them. Inside the loop callback you could use the storage append method https://laravel.com/docs/6.x/filesystem#storing-files to add the entry in your chosen format to a file. The easiest would be json decode but for sure you could create something similar like a syslog entry.
After appending it you can delete it.

You should use lazy collections or chunks to prevent loading millions of entries in the CLI runtime. Or even trigger a job for every activity ID. But this depends on your amount, needs and is the normal runtime tweaking.
