### ISSUE TITLE
I install activity log in laravel 5.4 version but data not insert in log activity table, only data insert in user table. 

### ISSUE THREAD

**Issue by vc-darshanbelani** [spatie/laravel-activitylog#637]
I am using the laravel 5.4 version. i configure activity log
but create time, not any data insert in activity log table only insert in the user table.
I attach the error screenshot. please help me.
![error](https://user-images.githubusercontent.com/49232223/69426582-93b85800-0d53-11ea-92c9-d0b17a67b4c0.JPG)

**Comment by Gummibeer** [comment]
Hey,

I'm sorry but Laravel 5.4 is out of support for a very long time (security support ended January 24th, 2018).
https://laravel.com/docs/5.7/releases#support-policy

After checking the release history you should stick to [v1.16.0](https://packagist.org/packages/spatie/laravel-activitylog#v1.16.0)? That's two major releases behind the current one.

I **highly** recommend to upgrade your Laravel installation and all related packages.

The line in question seems to be 
https://github.com/spatie/laravel-activitylog/blob/5e982c1b96c3ec89a62d2ef84d41b98415e62b08/src/Traits/DetectsChanges.php#L79
Could you provide some more details on your setup? The specific PHP, Laravel and package versions?

---

Okay, after a lot more research it seems that you are on [1.15.0](https://github.com/spatie/laravel-activitylog/releases/tag/1.15.0) which had a bug (seems like your described one). The bug got fixed in [1.15.1](https://github.com/spatie/laravel-activitylog/releases/tag/1.15.1).

https://github.com/spatie/laravel-activitylog/blob/37efa23d3770405aa763df4452faa8863f044942/src/Traits/DetectsChanges.php#L79

Without upgrading Laravel you should be able to upgrade to v1.16.0 - but you still should update your whole app/setup.
