### ISSUE TITLE
Does this slowdown the application?

### ISSUE THREAD

**Issue by gyan111** [spatie/laravel-activitylog#639]
Does logging slow down events?

Will it affect the response time that we usually get without logging?

**Comment by Gummibeer** [comment]
After all: yes, like every code you add to your application.
It has to load a service provider and run `n` DB queries (depending on your amount of actions).

How much this affects the performance depends on your PHP version, caching, amount of queries and speed of your DB and for sure the hardware of your app server.

Because you will likely only log "actions" (user has done/changed something) it will slightly (~2-10ms in a small machine setup) slow down your app during these action requests. But during normal GET requests without logging you won't notice any difference if you have enabled all caching (config, routes, container).

But you won't find any solution that doesn't affect the performance - even if you use a queue for the DB query you will have to create the queue entry.

**Comment by gyan111** [comment]
Thank You @Gummibeer for the quick reply.

Is there any way we can use this logging in specific functions only ?

Like if I create my own activity tracker then I will only add them to specific functions so that other functions will not be affected.

**Comment by Gummibeer** [comment]
This package logs nothing out of the box. We provide a trait you can use in your models to log all model activities (create, update, delete).
And with the helper function you can manually log activities in your code.

For further details you can read the docs https://docs.spatie.be/laravel-activitylog

**Comment by gyan111** [comment]
Thank you for your responses.
