### ISSUE TITLE
Can't log Translatable fields.

### ISSUE THREAD

**Issue by khaledBawz** [spatie/laravel-activitylog#647]
Hi,

I am trying to log only changed attributes by using ```protected static $logOnlyDirty = true;``` in my model, but this is not working if I'm using [translatable attributes package by Spatie](https://github.com/spatie/laravel-translatable). it logs only English attributes and I think that's because my app locale is English.

I am using Laravel Framework 6.9.0 and spatie/activity-log ^3.9

Thank you.

**Comment by Gummibeer** [comment]
Hey,

thanks for reaching out. Right now there isn't any special implementation to work with the translatable package. And yes, you are right that it logs english because of your app locale. This package only logs the attribute like `$model->attribute`. And for a lot of other scenarios it's wanted to use the accessors.
To fix this there should be another trait to handle the change detection/logging if the attribute is translatable. But this is something for another package.

**Comment by khaledBawz** [comment]
@Gummibeer Thanks for your comment. Could you please explain some more info for the code in the trait?

**Comment by Gummibeer** [comment]
I think that you will have to override.
 https://github.com/spatie/laravel-activitylog/blob/195887d440ba4664fdea4c2fb8fbc67adb34a291/src/Traits/DetectsChanges.php#L121-L150

Inside the loop you will have to check if the attribute is translatable.
https://github.com/spatie/laravel-translatable/blob/3a07be9e1e3cc9566c6d7274b613552d5cbf4b1a/src/HasTranslations.php#L141-L144

If so you will have to retrieve all translation data for this attribute.
https://github.com/spatie/laravel-translatable/blob/3a07be9e1e3cc9566c6d7274b613552d5cbf4b1a/src/HasTranslations.php#L63-L78

After this you will already be done (I think in theory).
Keep in mind that the `logChanges()` method is also called with the before updating original values.
https://github.com/spatie/laravel-activitylog/blob/195887d440ba4664fdea4c2fb8fbc67adb34a291/src/Traits/DetectsChanges.php#L17-L24

I haven't tested the logging with arrays - so it could be that you will have to adjust following if you only want to log dirty fields.
https://github.com/spatie/laravel-activitylog/blob/195887d440ba4664fdea4c2fb8fbc67adb34a291/src/Traits/DetectsChanges.php#L81-L119

If you need more help just ask. I'm happy to help. Possibly we will keep a list or even maintain the code in this repo as some kind of other spatie compatibility traits.
cc @freekmurze

**Comment by romualdbrisson** [comment]
+1

**Comment by DonDiegoAA** [comment]
+1

**Comment by Gummibeer** [comment]
@romualdbrisson & @DonDiegoAA could you please use the comment reactions or write full comments?
I've no idea what you want to upvote with your `+1`.
The only thing I see is that the combination of these two packages has some users which all seem unable to log the translated fields right now.
I would like to think about a solution/pattern that is extendable. For example something like the new Laravel custom casts.
But I still think about the responsibility of the class, the inputs/outputs and where we should hook it in.

Because this is a very specific issue that's based on a more general one I would like to solve the general one instead of implementing hundreds of custom solutions.

**Comment by DonDiegoAA** [comment]
Hello @Gummibeer ,

this +1 meant "I have this problem too and I'm interested in a solution".
Sorry, I realize it was the wrong way to do it.
I often use the spatie packages, and I take this opportunity to thank you for all this great work.
Since activitylog and translatable are two packages of spatie, I was hoping they would work well together, but I understand that it is not as easy as that.
For my part, when logOnlyDirty is true, if activitylog could record the entire json field if there has been a change, no matter the language, that would suit me very well. I will then take care in the history display to check which language has been changed.
But I also understand that this is not the ideal solution for you.
Thanks again

**Comment by indykoning** [comment]
In #801 i created a simple function you can override to implement your own way of collecting the data to report per attribute.
After this gets merged and released you could implement showing all translatable data by adding
```
    public function attributeDataToRecord($attribute)
    {
        if ($this->isTranslatableAttribute($attribute)) {
            return $this->getTranslations($attribute);
        }
    }
```
In your Model class, or in a trait that gets used in your models.

**Comment by ctf0** [comment]
it seems `tapActivity` can stop the model event so based on that, we can hook into it and add the data we want ex.

- create a new trait for translatables
- include spatie trait
- add the below

```php
public function tapActivity(Activity $activity, string $eventName)
{
    $keys  = array_keys(array_intersect_key($this->getDirty(), $this->getOriginal())); // get dirty only
    $keys  = array_intersect($keys, $this->translatable); // get translatable only
    $keys  = array_diff($keys, static::$logAttributesToIgnore); // get allowed only
    $old   = [];
    $new   = [];

    foreach ($keys as $key) {
        $old += [$key => $this->getOriginal($key)];
        $new += [$key => json_decode($this->getDirty()[$key], true)];
    }

    $activity->properties = [
        'old'        => $old,
        'attributes' => $new,
    ];
}
```

**Comment by ctf0** [comment]
**Update**

if the changed key is not in the current locale, the `tapActivity` wont work, this is due to as @Gummibeer stated 
> it logs english because of your app locale. This package only logs the attribute like `$model->attribute`

so to get around this, `$submitEmptyLogs` have to enabled

**Comment by Gummibeer** [comment]
I will close this issue even if v4 isn't released yet. But the task itself is done and I want to check which tasks are really open. Please keep an eye on #787
