### ISSUE TITLE
User Model not saving log attributes 

### ISSUE THREAD

**Issue by halah-m** [spatie/laravel-activitylog#654]
Hello, I have this issue that every other models save its logs attributes with creating/updating/deleting, but except the User model, its save description, causer and subject but not the attributes..

Example of a records from the database 
```
(id, log_name, description, subject_id, subject_type, causer_id, causer_type, properties, created_at, updated_at) VALUES (15, 'default', 'created', 4, 'App\\Models\\User', 1, 'App\\Models\\User', '{"ip": "127.0.0.1"}', '2020-01-26 16:35:51', '2020-01-26 16:35:51');
```

```
(id, log_name, description, subject_id, subject_type, causer_id, causer_type, properties, created_at, updated_at) VALUES (16, 'default', 'updated', 4, 'App\\Models\\User', 1, 'App\\Models\\User', '{"ip": "127.0.0.1"}', '2020-01-26 16:39:34', '2020-01-26 16:39:34');
``` 

You can see from the above examples that it didn't save properties->attributes like the other records.

My User model 

```PHP
class User extends Authenticatable
{
    use Notifiable;
    use LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $logAttributes = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

PHP version: 7.3.9 
Laravel version: 6.2

I use Laravel/Nova if thats makes a difference.

Thank you.

**Comment by Gummibeer** [comment]
Hey, the first thing I see is the not empty properties. Could you show the code that adds the `ip` to it?
My first thought is that this script doesn't add the IP but overrides the attribute.
Because the user itself isn't any different from a normal model and still triggers all events there's no simple reason why the package trait shouldn't work if it does in all your other models. And because the record itself is added there's also the proof that the event listener logic works.

Could you add a `dump()` for the `$changes` variable here in your vendor folder?
https://github.com/spatie/laravel-activitylog/blob/195887d440ba4664fdea4c2fb8fbc67adb34a291/src/Traits/DetectsChanges.php#L149
That's the method that resolves all the attribute values that should be logged. This method should trigger once for a create and twice for updates.

Another option to debug would be adding a `tapActivity()` method to your model and dump the whole activity model right before it's saved.
https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/#tap-activity-before-logged-from-event
