### ISSUE TITLE
Issue when having multiple primary key

### ISSUE THREAD

**Issue by Remi-AKO** [spatie/laravel-activitylog#655]
Hi,

I'm not able to make the package work on a table with 2 primary keys.

I tried on another table, and it works well, and this is the only notable difference

**Comment by Gummibeer** [comment]
Hey,
it could be the reason. We use `getKey()` method - so far I know eloquent does not support composite PKs.
Is there a reason you can't add a single AI PK and add the composite as unique?
Because we only use eloquent for database functionality I don't see any way to make it work with composite PKs.

**Comment by Remi-AKO** [comment]
Indeed that's the reason, because in my model i've rewrite the `getKey()` function.

Well this is a many to many relations table, so I have 2 ids which belongs to other table, et no unique id. So these 2 ids makes each row unique.

**Comment by Gummibeer** [comment]
There's no reason that prevents you from adding an AI PK to a pivot table and a composite unique constraint.
The moment your pivot table holds more data than the two keys it's more like a model than a simple pivot and could be treated as such.

**Comment by Remi-AKO** [comment]
Yes that's what i'm gonna do, thank's for your help
