### ISSUE TITLE
how to add index and show to events

### ISSUE THREAD

**Issue by amiiiiiink** [spatie/laravel-activitylog#663]
hi I want to add index and show log events into LogsActivity but when i change $events = collect
it wont detect which model is logging Call to undefined method App\\Profit::indexed()

**Comment by Gummibeer** [comment]
So far I know `indexed` isn't an eloquent model event. These events have to be fired as model event.

**Comment by amiiiiiink** [comment]
so we dont have any model event for index and show , am I right?
my question is that if I want to develope the trait LogsActivity to log index and show method automatically like what is happening for updated, created,deleted , what should I do?
I know I can write helper in index() and show() method but by using helpers i did not conside DRY

**Comment by Gummibeer** [comment]
These are the default model events:
https://github.com/illuminate/database/blob/4432b1a12d4156f50d5b04fc267d512011cde783/Eloquent/Concerns/HasEvents.php#L94-L104

`retrieved` could be used for the single show event. But keep in mind that this event is always triggered when the model is resolved and not only in a particular controller action.
Index is a much harder thing because multiple models are part of it. 

My recommendation would be a custom event you can fire and an eventlistener that creates the activity log.

**Comment by amiiiiiink** [comment]
so you mean we can t develope eventsToBeRecorded() method? in LogsActivity Trait?

**Comment by Gummibeer** [comment]
You can add and use all model events. The question is if you really want to log **every** `retrieved` event of the model. So even if they are loaded via relationship, artisan command or wherever. That's why I recommend a custom activity log.
