### ISSUE TITLE
On my user model i'm trying to use activitylogs package but I get the error Trait 'Spatie\activitylog\Traits\LogsActivity' not found

### ISSUE THREAD

**Issue by Kushal-u1462694** [spatie/laravel-activitylog#674]
Can Someone help please?

**Comment by Kushal-u1462694** [comment]
Can Someone help please?

**Comment by Gummibeer** [comment]
Hey @Kushal-u1462694 ,
I'm happy that you, how it seems, learn to code and are in your final year - if I've understood your [FYP repo](https://github.com/Kushal-u1462694/FYP). But the issues of an open source package aren't a learning/teaching place and your last issues were all related to PHP/Laravel basics and not any package issues. I really don't want to stop you from learning and also not from participating in the open source world!
But I want to link the [CONTRIBUTING](https://github.com/spatie/laravel-activitylog/blob/master/CONTRIBUTING.md) guidelines and quote two parts.

> Please be considerate towards maintainers when raising issues or presenting pull requests. Let's show the world that developers are civilized and selfless people.

> Attempt to replicate the problem, to ensure that it wasn't a coincidental incident.

Why these two? Because, depending on settings, the maintainers of packages will always receive a GitHub, email, slack, telegram ... notification if someone opens an issue/comments one. This is because we want to ensure high quality packages/code and take care of possible bugs in a fast and serious way.
So receiving a ton of "false alerts" will possibly prevent us from fixing a real bug - primary because most of us are maintainers of multiple packages which we have to moderate, maintain and handle.

So in conclusion I want to please you to respect the following things:
* Before you open an issue try to debug yourself, with a colleague/friend to ensure that it's not a simple typo "bug" and really related to the package.
* When you open an issue try to collect as much and prepared information, that could relate to the issue, as you can and post them in your initial issue description/comment.
* While discussing an issue you don't have to quote the comment you react to and again react with a single comment and not 2+.

To format your content you can use markdown - GitHub has a great article how to master it: https://guides.github.com/features/mastering-markdown/

Why all this? Because right now it feels kind of disrespectful if you use the issues like some kind of chat.
 
Some resources you can get help outside of GitHub issues:
* https://laracasts.com/
* https://laravelupandrunning.com/
* https://stackoverflow.com/
* http://larachat.co/

-----

Related to your issue - the first thing I spot is the lowercased `a` in the `activitylog` namespace part. Your IDE of choice should be able to detect such things and also mark it for you.
