### ISSUE TITLE
Compatibility with LTS (Laravel 5.1)

### ISSUE THREAD

**Issue by hackel** [spatie/laravel-activitylog#7]
Does this package actually use any Laravel 5.2 features?  I have just installed it in my Laravel LTS project by aliasing the version (`"laravel/framework": "5.1.36 as 5.2.21"`) and in my limited testing it appears to be working.  I would like to suggest maintaining LTS compatibility moving forward!

**Comment by freekmurze** [comment]
I would very much like the package to be L5.1 compatible. However, I you run the unit tests on L5.1 you'd see that the [`it_can_replace_the_placeholders`-test](https://github.com/spatie/laravel-activitylog/blob/master/tests/ActivityloggerTest.php#L160) fails. I'm thinking that's because the [`array_get`](https://github.com/spatie/laravel-activitylog/blob/8dfddb7d1ef6e75dbd3b6c78ae7d5f448aea0892/src/ActivityLogger.php#L167) function works slightly different in Laravel 5.1

I'd would accept a PR that makes the tests pass in L5.1.

**Comment by freekmurze** [comment]
Thanks to @JeroenNoten version 1.0.3 of the package is compatible with Laravel 5.1
