### ISSUE TITLE
vendor:publish commands produce no change

### ISSUE THREAD

**Issue by llhilton** [spatie/laravel-activitylog#70]
I have just installed the package via composer and added it to the config/app.php file as Spatie\Activitylog\ActivitylogServiceProvider::class
In running the commands for publishing the migrations and tags, I get told "nothing to publish for tag [migrations] / tag [config]
Commands I ran: 
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"

I confirmed that the package is in the vendor folder where expected. Just not sure why these aren't working. I'm not sure how to troubleshoot this, so any help would be appreciated!

**Comment by llhilton** [comment]
Ah-ha. I needed to clear the config cache using php artisan config:cache in order to make it work. So excited to implement this!

**Comment by marcusmoore** [comment]
If anyone else runs into this problem and happens to be upgrading from Spatie's old [activitylog](https://github.com/spatie/activitylog) package, the migration won't publish because it checks to see if there is a class named `CreateActivityLogTable` which already exists from the previous package. 

Simply comment out the line within the ServiceProvider, publish the migration, rename the class in the new migration file to something like `CreateNewActivityLogTable` and then run `composer dump` and you should be set.
