### ISSUE TITLE
multi language question

### ISSUE THREAD

**Issue by mscart** [spatie/laravel-activitylog#701]
Hi guys. 
I have two databases Category and CategoryDetails with models
Category
id, active
1 ,    1
CategoryDetails
id, category_id, name,     locale
3,     1,                test_ro,    ro
4,     1,                test_en,    en

How can i log the category names when i save the category

i tried with related model attributes in Category Model 
protected static $logAttributes = ['id','category_details.name];

public function category_details(){
        return $this->hasMany('\Path\To\CategoryDetailsModel);
    }
but returns null because is save the category first and after that i save the category details.
I have no ideea. 

Thanks

**Comment by Gummibeer** [comment]
Hey,
At first the related doesn't work because it's a one to many relationship.
The other side of the relationship has to be a single model.

Right now there's no way to log relationship changes on a different model. You will have to add activity logging on both models. The best solution will be the planned batches for v4 - this way the logs will have the same batch ID and can be joined by a cronjob or within your UI.

**Comment by mscart** [comment]
ok .. many thanks ..
