### ISSUE TITLE
How to track changes through the model's static::creating() method?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [spatie/laravel-activitylog#719]
How to track changes through the model's static::creating() method?

The sample code from the model, logic execution and data change in the database is not tracked here:

```php
public static function boot()
    {
        parent::boot();

        static::creating(function (Cost $cost) {
         // 
                User::update[
                //
                ];
        }
  }
```

**Comment by Gummibeer** [comment]
Hey,
so the creation of `Cost` is tracked but not the update of `User`?
Do both models use the `Spatie\Activitylog\Traits\LogsActivity`?
https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/

**Comment by oleksandr-roskovynskyi** [comment]
> Hey,
> so the creation of `Cost` is tracked but not the update of `User`?
> Do both models use the `Spatie\Activitylog\Traits\LogsActivity`?
> https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/

Yes, both models use a trait, but operations with the intermediate model are not logged

**Comment by oleksandr-roskovynskyi** [comment]
The problem remains relevant

**Comment by Gummibeer** [comment]
Hey, sorry for the delay.
I've added a testcase for the described scenario https://github.com/spatie/laravel-activitylog/commit/65a454c6314212b0f193860cd113dd1fa32b3d8d and it passes.
Do you have any logic or other package that suppresses events on the `User` model?

**Comment by oleksandr-roskovynskyi** [comment]
> Hey, sorry for the delay.
> I've added a testcase for the described scenario [65a454c](https://github.com/spatie/laravel-activitylog/commit/65a454c6314212b0f193860cd113dd1fa32b3d8d) and it passes.
> Do you have any logic or other package that suppresses events on the `User` model?

extends from others model (not model with this table where you add static::creating() method )

**Comment by Gummibeer** [comment]
That the `Issue719Sub` extends the `Article` model isn't important for this test. The `Article` model only unguards itself and defines the table to use.
And that both models use the same table is also not important because the events are triggered per model (php class) and not related to the underlying database in any way.
So the test remains still valid. But if you post a full code example (including all used models and the calling logic) or PR a failing test yourself it would be easier to find the issue. As long as there's no failing test in this repository it's impossible to fix a possible bug.
