### ISSUE TITLE
Change Column names 

### ISSUE THREAD

**Issue by jojie-webdev** [spatie/laravel-activitylog#732]
How to change column names on activity_logs table ?

Thank you,

**Comment by Gummibeer** [comment]
Hey,

you will have to edit the migration, model and all code occurrences of the renamed attributes.
I highly recommend to don't do it. At the end you won't use the package anymore and even a fix release could make your app unusable because we use any attribute in a code-snippet you haven't overridden. You will also have to upgrade your overrides yourself after every update.

**Comment by jojie-webdev** [comment]
I guessed you're right. anyways, Thanks for the info and advice :)
