### ISSUE TITLE
Creating Migrations after vendor:publish

### ISSUE THREAD

**Issue by humanwere** [spatie/laravel-activitylog#901]
**Describe the bug**
When I ran "php artisan vendor:publish --all" package creating migrations. But I already have the tables

**Versions (please complete the following information)**
- PHP: 8.0.5
- Database: PostgreSQL 13
- Laravel: 8.40.0
- Package: 4.0.0

**Comment by Gummibeer** [comment]
@freekmurze I believe that's an issue in the spatie package tools. 🤔
As that package publishes the migration it should check if the class already exists.

**Comment by pacoorozco** [comment]
I've been taking a look to the `spatie/laravel-package-tools` and I've seen where the bug is coming from. The `hasMigration()` method is expecting a snake case migration name, like `create_activity_log_table` but activitylog is using `CreateActivityLogTable` (see it [here](https://github.com/spatie/laravel-activitylog/blob/65c84263ae9ec66ac1282f5a34e0e725c5d0683d/src/ActivitylogServiceProvider.php#L20)).

There are two options:

1. Just change the name of the stubs to be snake case and update the `hasMigration()` call.
2. Modify the `migrationFileExists()` method in `spatie/laravel-package-tools` ([here](https://github.com/spatie/laravel-package-tools/blob/8655759ee47b95fdf45a94955c9b5f686e6a12b3/src/PackageServiceProvider.php#L135) to allow non-snake case migration names.

I'm going to submit a PR with option one.
